### PR TITLE
Add horizontal scroll support

### PR DESCRIPTION
**Pull request by JulianJorgensen**

### CODE REVIEW

**Comment by thebuilder** [comment]
Looks good! The Typescript definitions in `index.d.ts` should be updated to match the new props.

**Comment by JulianJorgensen** [comment]
@thebuilder 👍 done now, and I also added the prop to the readme.

**Comment by thebuilder** [comment]
Can you validate that this works?

I tried to create a story for it, but it just display 100% scrolled. Might be related to how storybook wraps the content. 🤔

**stories/ScrollPercentage.story.js**
```js
  .add('Horizontal', () => (
    <div style={{ width: '200vw' }}>
      <ScrollPercentage horizontal>
        {({ percentage }) => (
          <Header>{`Percentage scrolled: ${calcPercentage(
            percentage,
          )}%.`}</Header>
        )}
      </ScrollPercentage>
    </div>
  ))
```

**Comment by thebuilder** [comment]
If we start using another root, it does add some more complexity. We would also have to use the new root for the bounds calculations.

If we do build it, would it make sense to reuse its own ref as the (default) root? I think i need to see some actual examples/use cases.

**Comment by JulianJorgensen** [comment]
@thebuilder I think the default root should always be `window` as it is now - even if it's in horizontal mode.
Do you prefer looking at it yourself, or would you like me to make a PR?

**Comment by thebuilder** [comment]
I was thinking a prop like `useLocaleRoot` or `root="locale"`. Window should still be the default.

It's not something i have time to look into at the moment, but feel free to make a PR if you think it makes sense. 👍

**Pull request merged**
